insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Hog / Sausage Casing - Pork', 625.99);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Tortillas - Flour, 12', 91.55);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Veal - Inside', 326.91);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Garbag Bags - Black', 720.71);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Sprouts - Onion', 434.94);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Wine - Pinot Noir Latour', 99.08);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Plate - Foam, Bread And Butter', 826.37);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Apple - Macintosh', 729.63);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Paste - Black Olive', 178.03);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Wine - Cotes Du Rhone', 405.97);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Steampan - Foil', 440.78);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Towel - Roll White', 151.88);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Plasticforkblack', 911.48);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Crab Brie In Phyllo', 316.78);
insert into Product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Beer - True North Lager', 16.59);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Icecream - Dstk Super Cone', 352.11);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Parsley Italian - Fresh', 590.82);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Skewers - Bamboo', 350.12);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Tea - Grapefruit Green Tea', 825.0);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Truffle Cups - Red', 366.44);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Muffin Carrot - Individual', 378.13);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Macaroons - Homestyle Two Bit', 667.99);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Pasta - Cannelloni, Sheets, Fresh', 965.83);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Bowl 12 Oz - Showcase 92012', 381.2);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Wine - White, Riesling, Henry Of', 676.9);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Cinnamon - Ground', 394.72);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Nut - Macadamia', 357.72);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Pork - Caul Fat', 374.55);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Wine - Alsace Riesling Reserve', 10.65);
insert into product (id, name, price) values (NEXTVAL('hibernate_sequence'), 'Stock - Beef, White', 305.0);
